INSERT INTO departamentos(nombre_departamento) VALUES('Ahuachapán');
INSERT INTO departamentos(nombre_departamento) VALUES('Santa Ana');
INSERT INTO departamentos(nombre_departamento) VALUES('Sonsonate');
INSERT INTO departamentos(nombre_departamento) VALUES('Chalatenango');
INSERT INTO departamentos(nombre_departamento) VALUES('La Libertad');
INSERT INTO departamentos(nombre_departamento) VALUES('San Salvador');
INSERT INTO departamentos(nombre_departamento) VALUES('Cuscatlán');
INSERT INTO departamentos(nombre_departamento) VALUES('La Paz');
INSERT INTO departamentos(nombre_departamento) VALUES('Cabañas');
INSERT INTO departamentos(nombre_departamento) VALUES('San Vicente');
INSERT INTO departamentos(nombre_departamento) VALUES('Usulután');
INSERT INTO departamentos(nombre_departamento) VALUES('San Miguel');
INSERT INTO departamentos(nombre_departamento) VALUES('Morazán');
INSERT INTO departamentos(nombre_departamento) VALUES('La Unión');
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ahuachapan',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Apaneca',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Atiquizaya',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Concepcion De Ataco',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Refugio',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Guaymango',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jujutla',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Francisco Menendez',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Lorenzo',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Pedro Puxtla',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tacuba',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Turin',1);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Candelaria De La Frontera',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Coatepeque',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chalchuapa',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Congo',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Porvenir',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Masahuat',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Metapan',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Antonio Pajonal',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Sebastian Salitrillo',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Ana',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Rosa Guachipilin',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santiago De La Frontera',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Texistepeque',2);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Acajutla',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Armenia',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Caluco',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Cuisnahuat',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Isabel Ishuatan',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Izalco',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Juayua',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nahuizalco',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nahulingo',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Salcoatitan',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Antonio Del Monte',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Julian',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Catarina Masahuat',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santo Domingo De Guzman',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sonsonate',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sonzacate',3);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Agua Caliente',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Arcatao',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Azacualpa',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Citala',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Comalapa',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Concepcion Quezaltepeque',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chalatenango',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Dulce Nombre De Maria',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Carrizal',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Paraiso',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('La Laguna',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('La Palma',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('La Reina',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Las Vueltas',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nombre De Jesus',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nueva Concepcion',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nueva Trinidad',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ojos De Agua',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Potonico',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Antonio De La Cruz',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Antonio Los Ranchos',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Fernando',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Francisco Lempa',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Francisco Morazan',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Ignacio',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Isidro Labrador',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Jose Cancasque',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Las Flores',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Luis Del Carmen',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Miguel De Mercedes',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Rafael',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Rita',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tejutla',4);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Antiguo Cuscatlan',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ciudad Arce',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Colon',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Comasagua',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chiltiupan',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Huizucar',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jayaque',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jicalapa',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('La Libertad',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nuevo Cuscatlan',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Tecla',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Quezaltepeque',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sacacoyo',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Jose Villanueva',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Juan Opico',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Matias',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Pablo Tacachico',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tamanique',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Talnique',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Teotepeque',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tepecoyo',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Zaragoza',5);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Aguilares',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Apopa',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ayutuxtepeque',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Cuscatancingo',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Paisnal',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Guazapa',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ilopango',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Mejicanos',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nejapa',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Panchimalco',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Rosario De Mora',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Marcos',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Martin',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Salvador',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santiago Texacuangos',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santo Tomas',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Soyapango',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tonacatepeque',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ciudad Delgado',6);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Candelaria',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Cojutepeque',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Carmen',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Rosario',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Monte San Juan',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Oratorio De Concepcion',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Bartolome Perulapia',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Cristobal',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Jose Guayabal',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Pedro Perulapan',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Rafael Cedros',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Ramon',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Cruz Analquito',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Cruz Michapa',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Suchitoto',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tenancingo',7);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Cuyultitan',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Rosario',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jerusalen',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Mercedes La Ceiba',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Olocuilta',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Paraiso De Osorio',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Antonio Masahuat',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Emigdio',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Francisco Chinameca',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Juan Nonualco',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Juan Talpa',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Juan Tepezontes',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Luis Talpa',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Miguel Tepezontes',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Pedro Masahuat',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Pedro Nonualco',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Rafael Obrajuelo',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Maria Ostuma',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santiago Nonualco',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tapalhuaca',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Zacatecoluca',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Luis La Herradura',8);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Cinquera',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Guacotecti',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ilobasco',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jutiapa',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Isidro',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sensuntepeque',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tejutepeque',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Victoria',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Dolores',9);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Apastepeque',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Guadalupe',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Cayetano Istepeque',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Clara',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santo Domingo',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Esteban Catarina',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Ildefonso',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Lorenzo',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Sebastian',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Vicente',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tecoluca',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tepetitan',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Verapaz',10);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Alegria',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Berlin',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('California',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Concepcion Batres',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Triunfo',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ereguayquin',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Estanzuelas',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jiquilisco',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jucuapa',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jucuaran',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Mercedes Umaña',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nueva Granada',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ozatlan',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Puerto El Triunfo',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Agustin',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Buena Ventura',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Dionisio',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Elena',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Francisco Javier',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Maria',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santiago De Maria',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Tecapan',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Usulutan',11);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Carolina',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Ciudad Barrios',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Comacaran',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chapeltique',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chinameca',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chirilagua',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Transito',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Lolotique',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Moncagua',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nueva Guadalupe',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nuevo Eden De San Juan',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Quelepa',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Antonio',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Gerardo',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Jorge',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Luis De La Reina',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Miguel',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Rafael Oriente',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sesori',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Uluazapa',12);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Arambala',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Cacaopera',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Corinto',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Chilanga',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Delicias De Concepcion',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Divisadero',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Rosario',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Gualococti',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Guatajiagua',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Joateca',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jocoaitique',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Jocoro',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Lolotiquillo',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Meanguera',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Oscicala',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Perquin',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Carlos',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Fernando',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Francisco Gotera',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Isidro',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Simon',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sensembra',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Sociedad',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Torola',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Yamabal',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Yoloaiquin',13);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Anamoros',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Bolivar',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Concepcion De Oriente',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Conchagua',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Carmen',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('El Sauce',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Intipuca',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('La Union',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Lislique',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Meanguera Del Golfo',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Nueva Esparta',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Pasaquina',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Poloros',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Alejo',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('San Jose',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Santa Rosa De Lima',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Yayantique',14);
INSERT INTO municipios (nombre_municipio, id_departamento) VALUES('Yucuaiquin',14);